CREATE DATABASE IF NOT EXIST 'portal_berita'

USE DATABASE 'portal_berita'

CREATE TABLE `articles` (
  `ARTICLE_ID` int NOT NULL,
  `USER_ID` int DEFAULT NULL,
  `CATEGORY_ID` int DEFAULT NULL,
  `JUDUL_ARTICLE` longtext,
  `KONTEN_ARTICLE` text,
  `FOTO_ARTICLE` varchar(100) DEFAULT NULL,
  `TANGGAL_ARTICLE` datetime NOT NULL,
  `TANGGAL_DIBUAT` datetime NOT NULL
)

CREATE TABLE `bookmarks` (
  `BOOKMARK_ID` int NOT NULL,
  `ARTICLE_ID` int DEFAULT NULL,
  `USER_ID` int DEFAULT NULL,
  `CATEGORY_ID` int DEFAULT NULL,
  `JUDUL_BOOKMARK` varchar(100) DEFAULT NULL,
  `URL_BOOKMARK` varchar(100) DEFAULT NULL,
  `KONTEN_BOOKMARK` text,
  `FOTO_BOOKMARK` varchar(100) DEFAULT NULL,
  `TANGGAL_ BOOKMARK` datetime NOT NULL
)

CREATE TABLE `categories` (
  `CATEGORY_ID` int NOT NULL,
  `NAMA_CATEGORY` char(10) DEFAULT NULL
)

CREATE TABLE `users` (
  `USER_ID` int NOT NULL,
  `NAMA` varchar(100) DEFAULT NULL,
  `USERNAME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `FOTO_USER` varchar(100) DEFAULT NULL,
  `IS_ADMIN` tinyint NOT NULL DEFAULT '0'
) 

INSERT INTO `users` (`USER_ID`, `NAMA`, `USERNAME`, `EMAIL`, `PASSWORD`, `FOTO_USER`, `IS_ADMIN`) VALUES
(1, 'c', 'c', 'c', 'c', NULL, 0),
(2, 'b', 'b', 'b', 'b', NULL, 0),
(3, 'fadil', 'f', 'f', 'f', NULL, 0);

ALTER TABLE `articles`
  ADD PRIMARY KEY (`ARTICLE_ID`),
  ADD KEY `FK_ARTICLE_MEMILIKI_CATEGORY` (`CATEGORY_ID`),
  ADD KEY `FK_ARTICLE_MEMILIKI_USER` (`USER_ID`);

ALTER TABLE `bookmarks`
  ADD PRIMARY KEY (`BOOKMARK_ID`),
  ADD KEY `FK_BOOKMARK_MEMILIKI_ARTICLE` (`ARTICLE_ID`),
  ADD KEY `FK_BOOKMARK_MEMILIKI_CATEGORY` (`CATEGORY_ID`),
  ADD KEY `FK_BOOKMARK_MEMILIKI_USER` (`USER_ID`);

ALTER TABLE `categories`
  ADD PRIMARY KEY (`CATEGORY_ID`);

ALTER TABLE `users`
  ADD PRIMARY KEY (`USER_ID`);

ALTER TABLE `articles`
  MODIFY `ARTICLE_ID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

ALTER TABLE `bookmarks`
  MODIFY `BOOKMARK_ID` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `categories`
  MODIFY `CATEGORY_ID` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `users`
  MODIFY `USER_ID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

ALTER TABLE `articles`
  ADD CONSTRAINT `FK_ARTICLE_MEMILIKI_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `categories` (`CATEGORY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `FK_ARTICLE_MEMILIKI_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `bookmarks`
  ADD CONSTRAINT `FK_BOOKMARK_MEMILIKI_ARTICLE` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `articles` (`ARTICLE_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `FK_BOOKMARK_MEMILIKI_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `categories` (`CATEGORY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `FK_BOOKMARK_MEMILIKI_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;